# -*- coding: utf-8 -*-
"""Sentence similarity

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AwM9_biv-A9nfaqyXFfFvQu8kB4j-435
"""

pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer("all-MiniLM-L6-v2")

sentences = [
    "Patient has fever and cough",
    "The person is suffering from flu",
    "Stock market crashed today"
]

embeddings = model.encode(sentences)

similarity = util.cos_sim(embeddings, embeddings)
print(similarity)

similarity = util.cos_sim(embeddings, embeddings)
print(similarity)

pip install gensim

import gensim.downloader as api

# Load a small pretrained word2vec model from gensim-data
# We'll use "glove-wiki-gigaword-50" (50d vectors, ~70MB) for lightweight demo
model = api.load("glove-wiki-gigaword-50")

# Pick a demo word
word = "king"

# Get vector
vector = model[word]

# Get most similar words
similar = model.most_similar(word, topn=5)

vector[:10], similar  # show first 10 values of vector for brevity, plus top 5 similar words

import gensim.downloader as api
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# Load model
model = api.load("glove-wiki-gigaword-50")

# Target word
word = "india"

# Get similar words
similar_words = [w for w, _ in model.most_similar(word, topn=20)]

# Include original word
words = [word] + similar_words

# Get vectors
vectors = np.array([model[w] for w in words])

# Reduce to 2D for plotting
pca = PCA(n_components=2)
coords = pca.fit_transform(vectors)

# Cluster into 2 groups
kmeans = KMeans(n_clusters=2, random_state=42)
labels = kmeans.fit_predict(coords)

# Plot
plt.figure(figsize=(8,6))

for i, word in enumerate(words):
    x, y = coords[i]
    plt.scatter(x, y)
    plt.text(x+0.02, y+0.02, word, fontsize=9)

plt.title("Word Similarity Clusters")
plt.grid(True)
plt.show()

import gensim.downloader as api
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# Load model
model = api.load("glove-wiki-gigaword-50")

# Target word
word = "india"

# Get similar words
similar_words = [w for w, _ in model.most_similar(word, topn=20)]

# Include original word
words = [word] + similar_words

# Get vectors
vectors = np.array([model[w] for w in words])

# Reduce to 2D for plotting
pca = PCA(n_components=2)
coords = pca.fit_transform(vectors)

# Cluster into 2 groups
kmeans = KMeans(n_clusters=2, random_state=42)
labels = kmeans.fit_predict(coords)

# Plot
plt.figure(figsize=(8,6))

for i, word in enumerate(words):
    x, y = coords[i]
    plt.scatter(x, y)
    plt.text(x+0.02, y+0.02, word, fontsize=9)

plt.title("Word Similarity Clusters")
plt.grid(True)
plt.show()

import gensim.downloader as api
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Load pretrained embeddings
model = api.load("glove-wiki-gigaword-50")

# Words you want to visualize
words = [
    "king","queen","man","woman","prince","princess",
    "apple","banana","grape",
    "car","bus","train",
    "ocean","river","mountain"
]

# Keep only words present in vocab
words = [w for w in words if w in model]

# Get vectors
vectors = np.array([model[w] for w in words])

# Reduce dimensions to 2D
pca = PCA(n_components=2)
coords = pca.fit_transform(vectors)

# Plot
plt.figure(figsize=(9,7))

for i, word in enumerate(words):
    x, y = coords[i]
    plt.scatter(x, y)
    plt.text(x+0.03, y+0.03, word, fontsize=10)

plt.title("Semantic Word Embedding Map")
plt.xlabel("Component 1")
plt.ylabel("Component 2")
plt.grid(True)
plt.show()

from sentence_transformers import SentenceTransformer
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import numpy as np

# Load model
model = SentenceTransformer("all-MiniLM-L6-v2")

# Sentences
sentences = [
    "Patient has fever and cough",
    "The person is suffering from flu",
    "Stock market crashed today",
    "Stocks fell sharply in trading",
    "I love eating mangoes",
    "Bananas are my favorite fruit"
]

# Generate embeddings
embeddings = model.encode(sentences)

# Reduce dimensions to 2D
pca = PCA(n_components=2)
coords = pca.fit_transform(embeddings)

# Plot
plt.figure(figsize=(8,6))

for i, sentence in enumerate(sentences):
    x, y = coords[i]
    plt.scatter(x, y)
    plt.text(x+0.02, y+0.02, sentence, fontsize=9)

plt.title("Sentence Embedding Visualization")
plt.xlabel("Component 1")
plt.ylabel("Component 2")
plt.grid(True)
plt.show()